---
# tasks file for kube-firewall
- name: Enable ingress ports 
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items: 
    - 2379/tcp
    - 2380/tcp
    - 6443/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10253/tcp
    - 10254/tcp
    - 10255/tcp
    - 6783/tcp
    - 8472/udp
- name: Disable ingress port
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: disabled
    immediate: yes
  with_items: 
    - 8080/tcp